import assert from 'node:assert/strict';
import {confirmedMatch,paragraphs,selectedParagraph,layoutCandidate,sentenceBounds} from '../research_assistant/web/static/reader/selection_sync.js';
const a={artifact_id:'zh1',artifact_hash:'hash',page:1,rects:[[10,60,80,70]]};
const o={artifact_id:'en1',artifact_hash:'orig',page:2,rects:[[10,20,80,30]]};
const note={confirmed:true,archived:false,anchors:[a,o],source_links:[{translation_index:0,original_index:1,status:'user_confirmed'}]};
assert.deepEqual(confirmedMatch(a,[note]).anchor,o);
assert.equal(confirmedMatch(a,[{...note,archived:true}]).anchor,null);
assert.equal(confirmedMatch({...a,artifact_id:'zh2'},[note]).anchor,null);
assert.equal(confirmedMatch({...a,artifact_hash:'new'},[note]).anchor,null);
assert.equal(confirmedMatch(a,[note,{...note,anchors:[a,{...o,page:3}]}]).ambiguous,true);
const p=paragraphs([{text:'left1',rect:[10,60,80,70]},{text:'right1',rect:[150,60,220,70]},
 {text:'left2',rect:[10,46,80,56]},{text:'right2',rect:[150,46,220,56]}]);
assert.equal(p.length,2);
assert.ok(p.every(b=>b.rects.length===2));
const whole={...a,rects:p[0].rects,excerpt:p[0].excerpt};
assert.equal(layoutCandidate(whole,p,p).rect[0],10);
assert.equal(layoutCandidate(whole,p,[p[1]]),null);
assert.equal(layoutCandidate(whole,p,[p[0],p[0]]),null);
const word={...a,rects:[[10,60,16,70]],excerpt:'方法'};
assert.equal(confirmedMatch(word,[note]).anchor,null,'word must not reuse a containing paragraph link');
assert.equal(layoutCandidate(word,p,p),null,'one or two characters must not expand to a paragraph');
assert.equal(layoutCandidate(a,p,p),null,'one line of a multi-line paragraph is not a whole paragraph');
assert.equal(selectedParagraph({...whole,rects:[...p[0].rects,...p[1].rects]},p),null,'cross-column selection rejected');
assert.deepEqual(confirmedMatch(word,[{...note,anchors:[word,o]}]).anchor,o,'explicit word-level user link still works');
assert.equal(confirmedMatch({...a,excerpt:'方法'},[{...note,anchors:[{...a,excerpt:'方法的局限'},o]}]).anchor,null,'different excerpt is not the same confirmed selection');
assert.equal(selectedParagraph({...whole,excerpt:'left1'},p),null,'text completeness required even with inflated rectangles');
assert.equal(selectedParagraph({...whole,excerpt:'left1 left2'},p),p[0],'whitespace differences do not prevent a whole paragraph match');
assert.equal(selectedParagraph({...whole,rects:whole.rects.map(r=>[r[0],r[1]-1.5,r[2],r[3]+1.5])},p),p[0],'full text survives browser range font leading');
const chinese='前一句。患者接受治疗，症状得到改善。后一句！';
const patient=chinese.indexOf('患者');
const cb=sentenceBounds(chinese,patient,patient+2);
assert.equal(chinese.slice(...cb),'患者接受治疗，症状得到改善。','Chinese fragment expands to one sentence');
const english='Prior result. Patients improved after treatment. Final result.';
const improved=english.indexOf('improved');
const eb=sentenceBounds(english,improved,improved+8);
assert.equal(english.slice(...eb),'Patients improved after treatment.','English fragment expands to one sentence');
assert.equal(sentenceBounds(chinese,patient,chinese.indexOf('后一句')+2),null,'cross-sentence selection rejected');
assert.deepEqual(sentenceBounds('无标点短句',1,3),[0,5],'short unpunctuated text is one sentence');
console.log('23 selection-sync checks passed');
