// Run only against reading_preview.py --budget-fixture on 8766.
async (page) => {
  if (!page.url().startsWith("http://127.0.0.1:8766/")) throw Error("Isolated preview required");
  const config = await page.evaluate(() => fetch("/api/reading/settings").then(r => r.json()));
  if (config.model !== "fixture-no-network") throw Error("Mock provider required");
  await page.reload();
  await page.waitForFunction(() => [...document.querySelector("#papers").options].some(o => o.textContent === "scientific-en.pdf"));
  const checks = [];
  const check = (value, name) => { if (!value) throw Error(name); checks.push(name); };
  const loaded = async () => page.waitForFunction(() => document.querySelectorAll(".pane").length > 0 && [...document.querySelectorAll(".pane")].every(n => n.getAttribute("aria-busy") === "false" && n.querySelectorAll(".textLayer span").length > 10));
  const numbers = () => page.locator(".pane-controls input").evaluateAll(nodes => nodes.map(n => Number(n.value)));
  await page.setViewportSize({width:1440,height:1000});
  await page.locator("#papers").selectOption({label:"scientific-en.pdf"});
  await loaded();
  await page.locator("#compare").click();
  await page.waitForFunction(() => document.querySelectorAll(".pane").length === 2);
  await loaded();
  check(await page.locator("#sync-pages").isEnabled() && await page.locator("#sync-pages").isChecked(), "sync enabled for equal page counts");
  await page.locator(".pane").first().getByRole("button",{name:"下一页",exact:true}).click();
  await loaded();
  check(JSON.stringify(await numbers()) === "[2,2]", "left next turns both pages");
  await page.locator(".pane").last().getByRole("button",{name:"上一页",exact:true}).click();
  await loaded();
  check(JSON.stringify(await numbers()) === "[1,1]", "right previous turns both pages");
  await page.locator("#sync-pages").uncheck();
  await page.locator(".pane").first().getByRole("button",{name:"下一页",exact:true}).click();
  await loaded();
  check(JSON.stringify(await numbers()) === "[2,1]", "sync can be disabled");
  await page.locator("#sync-pages").check();
  await loaded();
  check(JSON.stringify(await numbers()) === "[2,2]", "reenabling follows left page");
  await page.locator(".pane-controls input").last().fill("1");
  await page.locator(".pane-controls input").last().press("Tab");
  await loaded();
  check(JSON.stringify(await numbers()) === "[1,1]", "typed page synchronizes");
  await page.evaluate(() => {
    const spans = [...document.querySelector(".textLayer").querySelectorAll("span")].filter(s => s.firstChild?.nodeType === 3 && s.textContent.trim());
    const span = spans.find(s => s.textContent.includes("baseline"));
    if (!span) throw Error("Synthetic baseline sentence missing");
    const start = span.textContent.indexOf("baseline");
    const r = document.createRange(); r.setStart(span.firstChild,start); r.setEnd(span.firstChild,start + "baseline".length);
    getSelection().removeAllRanges(); getSelection().addRange(r);
    document.querySelector(".pdf-page").dispatchEvent(new MouseEvent("mouseup",{bubbles:true}));
  });
  // P-083 tracks lost PDF whitespace separately; this check verifies sentence boundaries.
  await page.waitForFunction(() => document.querySelector("#selection").textContent.replace(/\s+/gu, "").includes("Thebaselineuseslexicalmatching."));
  check(await page.evaluate(() => getSelection().toString().replace(/\s+/gu, "") === "Thebaselineuseslexicalmatching."),
    "partial selection expands to one sentence, ignoring PDF whitespace");
  await page.locator("#highlight").click();
  await page.waitForFunction(() => document.querySelectorAll(".mark").length > 0);
  const noteText = "这是一条模拟验收笔记：方法保留原文证据，结论仍需核对。" + Date.now();
  await page.locator("#body").fill(noteText);
  await page.locator("#save").click();
  await page.waitForFunction(value => document.querySelector("#notes").textContent.includes(value), noteText);
  await loaded();
  const rects = () => page.locator(".pane").first().evaluate(n => {
    const p = n.querySelector(".pdf-page").getBoundingClientRect(), m = n.querySelector(".mark").getBoundingClientRect();
    return [(m.x-p.x)/p.width,(m.y-p.y)/p.height,m.width/p.width,m.height/p.height];
  });
  const before = await rects();
  await page.locator(".pane").first().getByRole("button",{name:"放大",exact:true}).click();
  await loaded();
  await page.locator(".pane").first().locator(".mark").first().waitFor({state:"visible"});
  const after = await rects();
  check(before.every((v,i) => Math.abs(v-after[i]) < .003), "highlight retains normalized position after zoom");
  await page.locator(".pane").first().getByRole("button",{name:"适应宽度",exact:true}).click();
  await loaded();
  await page.screenshot({path:"output/playwright/full-reader-desktop.png",fullPage:true});
  await page.locator("#focus").click();
  check(await page.locator("aside").isHidden(), "focus mode expands reading area");
  await loaded();
  await page.screenshot({path:"output/playwright/full-reader-focus.png",fullPage:true});
  await page.locator("#focus").click();
  await page.locator("#settings summary").click();
  check(await page.locator("#full-budget, #full-requests").count() === 0, "full translation has no total budget controls");
  // Confirmation is simulated ONLY after verifying the no-network fixture.
  await page.evaluate(() => { window.confirm = () => true; });
  await page.locator("#translate").click();
  await page.locator("#translation-start").click();
  await page.waitForFunction(() => document.querySelector("#jobs").textContent.includes("模拟完成"),{},{timeout:15000});
  check((await page.locator("#jobs").innerText()).includes("本次执行：100 token（输入 70 / 输出 30）"), "mock attempt input/output usage displayed");
  await page.locator("#retranslate").click();
  await page.locator("#translation-start").click();
  await page.waitForFunction(() => document.querySelector("#jobs .running"),{},{timeout:10000});
  await page.getByRole("button",{name:"停止任务",exact:true}).first().click();
  await page.waitForFunction(() => !document.querySelector("#jobs .running"),{},{timeout:10000});
  check((await page.locator("#jobs").innerText()).includes("100 token"), "stopped task retains usage");
  await page.setViewportSize({width:390,height:844});
  await loaded();
  await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth);
  check(true, "mobile has no document overflow");
  await page.screenshot({path:"output/playwright/full-reader-mobile.png",fullPage:true});
  await page.reload();
  await page.waitForFunction(() => [...document.querySelector("#papers").options].some(o => o.textContent === "scientific-en.pdf"));
  await page.locator("#papers").selectOption({label:"scientific-en.pdf"}); await loaded();
  check((await page.locator("#notes").innerText()).includes("模拟验收笔记"), "notes survive refresh");
  check(await page.locator(".mark").count() > 0, "highlights survive refresh");
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(value => sessionStorage.setItem("full-reader-checks", JSON.stringify(value)), checks);
  return {provider:"mock, no paid calls",passed:checks.length,checks};
}
